module Board.Rand
    exposing
        ( board
        , Seed
        )

import Config.Lang as Lang exposing (..)
import Random.Extra exposing (combine, constant, frequency)
import Random exposing (..)
import Routing.Shape as Shape exposing (..)


type alias Seed =
    Int



-- GENERATOR


board : Lang -> Shape -> Random.Seed -> ( List Char, Random.Seed )
board lang shape seed =
    case lang of
        English ->
            boardWithSize englishLetter englishPair shape seed


boardWithSize : Generator Char -> (Char -> Generator Char) -> Shape -> Random.Seed -> ( List Char, Random.Seed )
boardWithSize genChar genPair size seed =
    case size of
        Shape x y ->
            if x >= 0 && y >= 0 then
                List.range 1 (x * y)
                    |> List.foldl (nextLetter genChar genPair) ( [], seed )
            else
                ( [], seed )


nextLetter : Generator Char -> (Char -> Generator Char) -> Int -> ( List Char, Random.Seed ) -> ( List Char, Random.Seed )
nextLetter genChar genPair _ ( chars, seed ) =
    let
        ( c, newSeed ) =
            Random.step genChar seed
    in
        ( c :: chars, newSeed )


englishLetter : Generator Char
englishLetter =
    frequency
        [ ( 0.1202, constant 'E' )
        , ( 0.091, constant 'T' )
        , ( 0.0812, constant 'A' )
        , ( 0.0768, constant 'O' )
        , ( 0.0731, constant 'I' )
        , ( 0.0695, constant 'N' )
        , ( 0.0628, constant 'S' )
        , ( 0.0602, constant 'R' )
        , ( 0.0592, constant 'H' )
        , ( 0.0432, constant 'D' )
        , ( 0.0398, constant 'L' )
        , ( 0.0288, constant 'U' )
        , ( 0.0271, constant 'C' )
        , ( 0.0261, constant 'M' )
        , ( 0.023, constant 'F' )
        , ( 0.0211, constant 'Y' )
        , ( 0.0209, constant 'W' )
        , ( 0.0203, constant 'G' )
        , ( 0.0182, constant 'P' )
        , ( 0.0149, constant 'B' )
        , ( 0.0111, constant 'V' )
        , ( 0.0069, constant 'K' )
        , ( 0.0017, constant 'X' )
        , ( 0.0011, constant 'Q' )
        , ( 0.001, constant 'J' )
        , ( 0.0007, constant 'Z' )
        ]


englishPair : Char -> Generator Char
englishPair firstLetter =
    case firstLetter of
        'A' ->
            frequency
                [ ( 1, constant 'A' )
                , ( 20, constant 'B' )
                , ( 33, constant 'C' )
                , ( 52, constant 'D' )
                , ( 0, constant 'E' )
                , ( 12, constant 'F' )
                , ( 18, constant 'G' )
                , ( 5, constant 'H' )
                , ( 39, constant 'I' )
                , ( 1, constant 'J' )
                , ( 12, constant 'K' )
                , ( 57, constant 'L' )
                , ( 26, constant 'M' )
                , ( 181, constant 'N' )
                , ( 1, constant 'O' )
                , ( 20, constant 'P' )
                , ( 1, constant 'Q' )
                , ( 75, constant 'R' )
                , ( 95, constant 'S' )
                , ( 104, constant 'T' )
                , ( 9, constant 'U' )
                , ( 20, constant 'V' )
                , ( 13, constant 'W' )
                , ( 1, constant 'X' )
                , ( 26, constant 'Y' )
                , ( 1, constant 'Z' )
                ]

        'B' ->
            frequency
                [ ( 11, constant 'A' )
                , ( 1, constant 'B' )
                , ( 0, constant 'C' )
                , ( 0, constant 'D' )
                , ( 47, constant 'E' )
                , ( 0, constant 'F' )
                , ( 0, constant 'G' )
                , ( 0, constant 'H' )
                , ( 6, constant 'I' )
                , ( 1, constant 'J' )
                , ( 0, constant 'K' )
                , ( 17, constant 'L' )
                , ( 0, constant 'M' )
                , ( 0, constant 'N' )
                , ( 19, constant 'O' )
                , ( 0, constant 'P' )
                , ( 0, constant 'Q' )
                , ( 11, constant 'R' )
                , ( 2, constant 'S' )
                , ( 1, constant 'T' )
                , ( 21, constant 'U' )
                , ( 0, constant 'V' )
                , ( 0, constant 'W' )
                , ( 0, constant 'X' )
                , ( 11, constant 'Y' )
                , ( 0, constant 'Z' )
                ]

        'C' ->
            frequency
                [ ( 31, constant 'A' )
                , ( 0, constant 'B' )
                , ( 4, constant 'C' )
                , ( 0, constant 'D' )
                , ( 38, constant 'E' )
                , ( 0, constant 'F' )
                , ( 0, constant 'G' )
                , ( 38, constant 'H' )
                , ( 10, constant 'I' )
                , ( 0, constant 'J' )
                , ( 18, constant 'K' )
                , ( 9, constant 'L' )
                , ( 0, constant 'M' )
                , ( 0, constant 'N' )
                , ( 45, constant 'O' )
                , ( 0, constant 'P' )
                , ( 1, constant 'Q' )
                , ( 11, constant 'R' )
                , ( 1, constant 'S' )
                , ( 15, constant 'T' )
                , ( 7, constant 'U' )
                , ( 0, constant 'V' )
                , ( 0, constant 'W' )
                , ( 0, constant 'X' )
                , ( 1, constant 'Y' )
                , ( 0, constant 'Z' )
                ]

        'D' ->
            frequency
                [ ( 48, constant 'A' )
                , ( 20, constant 'B' )
                , ( 9, constant 'C' )
                , ( 13, constant 'D' )
                , ( 57, constant 'E' )
                , ( 11, constant 'F' )
                , ( 7, constant 'G' )
                , ( 25, constant 'H' )
                , ( 50, constant 'I' )
                , ( 3, constant 'J' )
                , ( 1, constant 'K' )
                , ( 11, constant 'L' )
                , ( 14, constant 'M' )
                , ( 16, constant 'N' )
                , ( 41, constant 'O' )
                , ( 6, constant 'P' )
                , ( 0, constant 'Q' )
                , ( 14, constant 'R' )
                , ( 35, constant 'S' )
                , ( 56, constant 'T' )
                , ( 10, constant 'U' )
                , ( 2, constant 'V' )
                , ( 19, constant 'W' )
                , ( 0, constant 'X' )
                , ( 10, constant 'Y' )
                , ( 0, constant 'Z' )
                ]

        'E' ->
            frequency
                [ ( 110, constant 'A' )
                , ( 23, constant 'B' )
                , ( 45, constant 'C' )
                , ( 126, constant 'D' )
                , ( 48, constant 'E' )
                , ( 30, constant 'F' )
                , ( 15, constant 'G' )
                , ( 33, constant 'H' )
                , ( 41, constant 'I' )
                , ( 3, constant 'J' )
                , ( 5, constant 'K' )
                , ( 55, constant 'L' )
                , ( 47, constant 'M' )
                , ( 111, constant 'N' )
                , ( 33, constant 'O' )
                , ( 28, constant 'P' )
                , ( 2, constant 'Q' )
                , ( 169, constant 'R' )
                , ( 115, constant 'S' )
                , ( 83, constant 'T' )
                , ( 6, constant 'U' )
                , ( 24, constant 'V' )
                , ( 50, constant 'W' )
                , ( 9, constant 'X' )
                , ( 26, constant 'Y' )
                , ( 0, constant 'Z' )
                ]

        'F' ->
            frequency
                [ ( 25, constant 'A' )
                , ( 2, constant 'B' )
                , ( 3, constant 'C' )
                , ( 2, constant 'D' )
                , ( 20, constant 'E' )
                , ( 11, constant 'F' )
                , ( 1, constant 'G' )
                , ( 8, constant 'H' )
                , ( 23, constant 'I' )
                , ( 1, constant 'J' )
                , ( 0, constant 'K' )
                , ( 8, constant 'L' )
                , ( 5, constant 'M' )
                , ( 1, constant 'N' )
                , ( 40, constant 'O' )
                , ( 2, constant 'P' )
                , ( 0, constant 'Q' )
                , ( 16, constant 'R' )
                , ( 5, constant 'S' )
                , ( 37, constant 'T' )
                , ( 8, constant 'U' )
                , ( 0, constant 'V' )
                , ( 3, constant 'W' )
                , ( 0, constant 'X' )
                , ( 2, constant 'Y' )
                , ( 0, constant 'Z' )
                ]

        'G' ->
            frequency
                [ ( 24, constant 'A' )
                , ( 3, constant 'B' )
                , ( 2, constant 'C' )
                , ( 2, constant 'D' )
                , ( 28, constant 'E' )
                , ( 3, constant 'F' )
                , ( 4, constant 'G' )
                , ( 35, constant 'H' )
                , ( 18, constant 'I' )
                , ( 1, constant 'J' )
                , ( 0, constant 'K' )
                , ( 7, constant 'L' )
                , ( 3, constant 'M' )
                , ( 4, constant 'N' )
                , ( 23, constant 'O' )
                , ( 1, constant 'P' )
                , ( 0, constant 'Q' )
                , ( 12, constant 'R' )
                , ( 9, constant 'S' )
                , ( 16, constant 'T' )
                , ( 7, constant 'U' )
                , ( 0, constant 'V' )
                , ( 5, constant 'W' )
                , ( 0, constant 'X' )
                , ( 1, constant 'Y' )
                , ( 0, constant 'Z' )
                ]

        'H' ->
            frequency
                [ ( 114, constant 'A' )
                , ( 2, constant 'B' )
                , ( 2, constant 'C' )
                , ( 1, constant 'D' )
                , ( 302, constant 'E' )
                , ( 2, constant 'F' )
                , ( 1, constant 'G' )
                , ( 6, constant 'H' )
                , ( 97, constant 'I' )
                , ( 0, constant 'J' )
                , ( 0, constant 'K' )
                , ( 2, constant 'L' )
                , ( 3, constant 'M' )
                , ( 1, constant 'N' )
                , ( 49, constant 'O' )
                , ( 1, constant 'P' )
                , ( 0, constant 'Q' )
                , ( 8, constant 'R' )
                , ( 5, constant 'S' )
                , ( 32, constant 'T' )
                , ( 8, constant 'U' )
                , ( 0, constant 'V' )
                , ( 4, constant 'W' )
                , ( 0, constant 'X' )
                , ( 4, constant 'Y' )
                , ( 0, constant 'Z' )
                ]

        'I' ->
            frequency
                [ ( 10, constant 'A' )
                , ( 5, constant 'B' )
                , ( 32, constant 'C' )
                , ( 33, constant 'D' )
                , ( 23, constant 'E' )
                , ( 17, constant 'F' )
                , ( 25, constant 'G' )
                , ( 6, constant 'H' )
                , ( 1, constant 'I' )
                , ( 1, constant 'J' )
                , ( 8, constant 'K' )
                , ( 37, constant 'L' )
                , ( 37, constant 'M' )
                , ( 179, constant 'N' )
                , ( 24, constant 'O' )
                , ( 6, constant 'P' )
                , ( 0, constant 'Q' )
                , ( 27, constant 'R' )
                , ( 86, constant 'S' )
                , ( 93, constant 'T' )
                , ( 1, constant 'U' )
                , ( 14, constant 'V' )
                , ( 7, constant 'W' )
                , ( 2, constant 'X' )
                , ( 0, constant 'Y' )
                , ( 2, constant 'Z' )
                ]

        'J' ->
            frequency
                [ ( 2, constant 'A' )
                , ( 0, constant 'B' )
                , ( 0, constant 'C' )
                , ( 0, constant 'D' )
                , ( 2, constant 'E' )
                , ( 0, constant 'F' )
                , ( 0, constant 'G' )
                , ( 0, constant 'H' )
                , ( 3, constant 'I' )
                , ( 0, constant 'J' )
                , ( 0, constant 'K' )
                , ( 0, constant 'L' )
                , ( 0, constant 'M' )
                , ( 0, constant 'N' )
                , ( 3, constant 'O' )
                , ( 0, constant 'P' )
                , ( 0, constant 'Q' )
                , ( 0, constant 'R' )
                , ( 0, constant 'S' )
                , ( 0, constant 'T' )
                , ( 8, constant 'U' )
                , ( 0, constant 'V' )
                , ( 0, constant 'W' )
                , ( 0, constant 'X' )
                , ( 0, constant 'Y' )
                , ( 0, constant 'Z' )
                ]

        'K' ->
            frequency
                [ ( 6, constant 'A' )
                , ( 1, constant 'B' )
                , ( 1, constant 'C' )
                , ( 1, constant 'D' )
                , ( 29, constant 'E' )
                , ( 1, constant 'F' )
                , ( 0, constant 'G' )
                , ( 2, constant 'H' )
                , ( 14, constant 'I' )
                , ( 0, constant 'J' )
                , ( 0, constant 'K' )
                , ( 2, constant 'L' )
                , ( 1, constant 'M' )
                , ( 9, constant 'N' )
                , ( 4, constant 'O' )
                , ( 0, constant 'P' )
                , ( 0, constant 'Q' )
                , ( 0, constant 'R' )
                , ( 5, constant 'S' )
                , ( 4, constant 'T' )
                , ( 1, constant 'U' )
                , ( 0, constant 'V' )
                , ( 2, constant 'W' )
                , ( 0, constant 'X' )
                , ( 2, constant 'Y' )
                , ( 0, constant 'Z' )
                ]

        'L' ->
            frequency
                [ ( 0, constant 'A' )
                , ( 0, constant 'B' )
                , ( 0, constant 'C' )
                , ( 0, constant 'D' )
                , ( 0, constant 'E' )
                , ( 0, constant 'F' )
                , ( 0, constant 'G' )
                , ( 0, constant 'H' )
                , ( 0, constant 'I' )
                , ( 0, constant 'J' )
                , ( 0, constant 'K' )
                , ( 0, constant 'L' )
                , ( 0, constant 'M' )
                , ( 0, constant 'N' )
                , ( 0, constant 'O' )
                , ( 0, constant 'P' )
                , ( 0, constant 'Q' )
                , ( 0, constant 'R' )
                , ( 0, constant 'S' )
                , ( 0, constant 'T' )
                , ( 0, constant 'U' )
                , ( 0, constant 'V' )
                , ( 0, constant 'W' )
                , ( 0, constant 'X' )
                , ( 0, constant 'Y' )
                , ( 0, constant 'Z' )
                ]

        'M' ->
            frequency
                [ ( 44, constant 'A' )
                , ( 7, constant 'B' )
                , ( 1, constant 'C' )
                , ( 1, constant 'D' )
                , ( 68, constant 'E' )
                , ( 2, constant 'F' )
                , ( 1, constant 'G' )
                , ( 3, constant 'H' )
                , ( 25, constant 'I' )
                , ( 0, constant 'J' )
                , ( 0, constant 'K' )
                , ( 1, constant 'L' )
                , ( 5, constant 'M' )
                , ( 2, constant 'N' )
                , ( 29, constant 'O' )
                , ( 11, constant 'P' )
                , ( 0, constant 'Q' )
                , ( 3, constant 'R' )
                , ( 10, constant 'S' )
                , ( 9, constant 'T' )
                , ( 8, constant 'U' )
                , ( 0, constant 'V' )
                , ( 4, constant 'W' )
                , ( 0, constant 'X' )
                , ( 18, constant 'Y' )
                , ( 0, constant 'Z' )
                ]

        'N' ->
            frequency
                [ ( 40, constant 'A' )
                , ( 7, constant 'B' )
                , ( 25, constant 'C' )
                , ( 146, constant 'D' )
                , ( 66, constant 'E' )
                , ( 8, constant 'F' )
                , ( 92, constant 'G' )
                , ( 16, constant 'H' )
                , ( 33, constant 'I' )
                , ( 2, constant 'J' )
                , ( 8, constant 'K' )
                , ( 9, constant 'L' )
                , ( 7, constant 'M' )
                , ( 8, constant 'N' )
                , ( 60, constant 'O' )
                , ( 4, constant 'P' )
                , ( 1, constant 'Q' )
                , ( 3, constant 'R' )
                , ( 33, constant 'S' )
                , ( 106, constant 'T' )
                , ( 6, constant 'U' )
                , ( 2, constant 'V' )
                , ( 12, constant 'W' )
                , ( 0, constant 'X' )
                , ( 11, constant 'Y' )
                , ( 0, constant 'Z' )
                ]

        'O' ->
            frequency
                [ ( 16, constant 'A' )
                , ( 12, constant 'B' )
                , ( 13, constant 'C' )
                , ( 18, constant 'D' )
                , ( 5, constant 'E' )
                , ( 80, constant 'F' )
                , ( 7, constant 'G' )
                , ( 11, constant 'H' )
                , ( 12, constant 'I' )
                , ( 1, constant 'J' )
                , ( 13, constant 'K' )
                , ( 26, constant 'L' )
                , ( 48, constant 'M' )
                , ( 106, constant 'N' )
                , ( 36, constant 'O' )
                , ( 15, constant 'P' )
                , ( 0, constant 'Q' )
                , ( 84, constant 'R' )
                , ( 28, constant 'S' )
                , ( 57, constant 'T' )
                , ( 115, constant 'U' )
                , ( 12, constant 'V' )
                , ( 46, constant 'W' )
                , ( 0, constant 'X' )
                , ( 5, constant 'Y' )
                , ( 1, constant 'Z' )
                ]

        'P' ->
            frequency
                [ ( 23, constant 'A' )
                , ( 1, constant 'B' )
                , ( 0, constant 'C' )
                , ( 0, constant 'D' )
                , ( 30, constant 'E' )
                , ( 1, constant 'F' )
                , ( 0, constant 'G' )
                , ( 3, constant 'H' )
                , ( 12, constant 'I' )
                , ( 0, constant 'J' )
                , ( 0, constant 'K' )
                , ( 15, constant 'L' )
                , ( 1, constant 'M' )
                , ( 0, constant 'N' )
                , ( 21, constant 'O' )
                , ( 10, constant 'P' )
                , ( 0, constant 'Q' )
                , ( 18, constant 'R' )
                , ( 5, constant 'S' )
                , ( 11, constant 'T' )
                , ( 6, constant 'U' )
                , ( 0, constant 'V' )
                , ( 1, constant 'W' )
                , ( 0, constant 'X' )
                , ( 1, constant 'Y' )
                , ( 0, constant 'Z' )
                ]

        'Q' ->
            frequency
                [ ( 0, constant 'A' )
                , ( 0, constant 'B' )
                , ( 0, constant 'C' )
                , ( 0, constant 'D' )
                , ( 0, constant 'E' )
                , ( 0, constant 'F' )
                , ( 0, constant 'G' )
                , ( 0, constant 'H' )
                , ( 0, constant 'I' )
                , ( 0, constant 'J' )
                , ( 0, constant 'K' )
                , ( 0, constant 'L' )
                , ( 0, constant 'M' )
                , ( 0, constant 'N' )
                , ( 0, constant 'O' )
                , ( 0, constant 'P' )
                , ( 0, constant 'Q' )
                , ( 0, constant 'R' )
                , ( 0, constant 'S' )
                , ( 0, constant 'T' )
                , ( 9, constant 'U' )
                , ( 0, constant 'V' )
                , ( 0, constant 'W' )
                , ( 0, constant 'X' )
                , ( 0, constant 'Y' )
                , ( 0, constant 'Z' )
                ]

        'R' ->
            frequency
                [ ( 50, constant 'A' )
                , ( 7, constant 'B' )
                , ( 10, constant 'C' )
                , ( 20, constant 'D' )
                , ( 133, constant 'E' )
                , ( 8, constant 'F' )
                , ( 10, constant 'G' )
                , ( 12, constant 'H' )
                , ( 50, constant 'I' )
                , ( 1, constant 'J' )
                , ( 8, constant 'K' )
                , ( 10, constant 'L' )
                , ( 14, constant 'M' )
                , ( 16, constant 'N' )
                , ( 55, constant 'O' )
                , ( 6, constant 'P' )
                , ( 0, constant 'Q' )
                , ( 14, constant 'R' )
                , ( 37, constant 'S' )
                , ( 42, constant 'T' )
                , ( 12, constant 'U' )
                , ( 4, constant 'V' )
                , ( 11, constant 'W' )
                , ( 0, constant 'X' )
                , ( 21, constant 'Y' )
                , ( 0, constant 'Z' )
                ]

        'S' ->
            frequency
                [ ( 67, constant 'A' )
                , ( 11, constant 'B' )
                , ( 17, constant 'C' )
                , ( 7, constant 'D' )
                , ( 74, constant 'E' )
                , ( 11, constant 'F' )
                , ( 4, constant 'G' )
                , ( 50, constant 'H' )
                , ( 49, constant 'I' )
                , ( 2, constant 'J' )
                , ( 6, constant 'K' )
                , ( 13, constant 'L' )
                , ( 12, constant 'M' )
                , ( 10, constant 'N' )
                , ( 57, constant 'O' )
                , ( 20, constant 'P' )
                , ( 2, constant 'Q' )
                , ( 4, constant 'R' )
                , ( 43, constant 'S' )
                , ( 109, constant 'T' )
                , ( 20, constant 'U' )
                , ( 2, constant 'V' )
                , ( 24, constant 'W' )
                , ( 0, constant 'X' )
                , ( 4, constant 'Y' )
                , ( 0, constant 'Z' )
                ]

        'T' ->
            frequency
                [ ( 59, constant 'A' )
                , ( 10, constant 'B' )
                , ( 11, constant 'C' )
                , ( 7, constant 'D' )
                , ( 75, constant 'E' )
                , ( 9, constant 'F' )
                , ( 3, constant 'G' )
                , ( 330, constant 'H' )
                , ( 76, constant 'I' )
                , ( 1, constant 'J' )
                , ( 2, constant 'K' )
                , ( 17, constant 'L' )
                , ( 11, constant 'M' )
                , ( 7, constant 'N' )
                , ( 115, constant 'O' )
                , ( 4, constant 'P' )
                , ( 0, constant 'Q' )
                , ( 28, constant 'R' )
                , ( 34, constant 'S' )
                , ( 56, constant 'T' )
                , ( 17, constant 'U' )
                , ( 1, constant 'V' )
                , ( 31, constant 'W' )
                , ( 0, constant 'X' )
                , ( 16, constant 'Y' )
                , ( 0, constant 'Z' )
                ]

        'U' ->
            frequency
                [ ( 7, constant 'A' )
                , ( 5, constant 'B' )
                , ( 12, constant 'C' )
                , ( 7, constant 'D' )
                , ( 7, constant 'E' )
                , ( 2, constant 'F' )
                , ( 14, constant 'G' )
                , ( 2, constant 'H' )
                , ( 8, constant 'I' )
                , ( 0, constant 'J' )
                , ( 1, constant 'K' )
                , ( 34, constant 'L' )
                , ( 8, constant 'M' )
                , ( 36, constant 'N' )
                , ( 1, constant 'O' )
                , ( 16, constant 'P' )
                , ( 0, constant 'Q' )
                , ( 44, constant 'R' )
                , ( 35, constant 'S' )
                , ( 48, constant 'T' )
                , ( 0, constant 'U' )
                , ( 0, constant 'V' )
                , ( 2, constant 'W' )
                , ( 0, constant 'X' )
                , ( 1, constant 'Y' )
                , ( 0, constant 'Z' )
                ]

        'V' ->
            frequency
                [ ( 5, constant 'A' )
                , ( 0, constant 'B' )
                , ( 0, constant 'C' )
                , ( 0, constant 'D' )
                , ( 65, constant 'E' )
                , ( 0, constant 'F' )
                , ( 0, constant 'G' )
                , ( 0, constant 'H' )
                , ( 11, constant 'I' )
                , ( 0, constant 'J' )
                , ( 0, constant 'K' )
                , ( 0, constant 'L' )
                , ( 0, constant 'M' )
                , ( 0, constant 'N' )
                , ( 4, constant 'O' )
                , ( 0, constant 'P' )
                , ( 0, constant 'Q' )
                , ( 0, constant 'R' )
                , ( 0, constant 'S' )
                , ( 0, constant 'T' )
                , ( 0, constant 'U' )
                , ( 0, constant 'V' )
                , ( 0, constant 'W' )
                , ( 0, constant 'X' )
                , ( 1, constant 'Y' )
                , ( 0, constant 'Z' )
                ]

        'W' ->
            frequency
                [ ( 66, constant 'A' )
                , ( 1, constant 'B' )
                , ( 1, constant 'C' )
                , ( 2, constant 'D' )
                , ( 39, constant 'E' )
                , ( 1, constant 'F' )
                , ( 0, constant 'G' )
                , ( 44, constant 'H' )
                , ( 39, constant 'I' )
                , ( 0, constant 'J' )
                , ( 0, constant 'K' )
                , ( 2, constant 'L' )
                , ( 1, constant 'M' )
                , ( 12, constant 'N' )
                , ( 29, constant 'O' )
                , ( 0, constant 'P' )
                , ( 0, constant 'Q' )
                , ( 3, constant 'R' )
                , ( 4, constant 'S' )
                , ( 4, constant 'T' )
                , ( 1, constant 'U' )
                , ( 0, constant 'V' )
                , ( 2, constant 'W' )
                , ( 0, constant 'X' )
                , ( 1, constant 'Y' )
                , ( 0, constant 'Z' )
                ]

        'X' ->
            frequency
                [ ( 1, constant 'A' )
                , ( 0, constant 'B' )
                , ( 2, constant 'C' )
                , ( 0, constant 'D' )
                , ( 1, constant 'E' )
                , ( 0, constant 'F' )
                , ( 0, constant 'G' )
                , ( 0, constant 'H' )
                , ( 2, constant 'I' )
                , ( 0, constant 'J' )
                , ( 0, constant 'K' )
                , ( 0, constant 'L' )
                , ( 0, constant 'M' )
                , ( 0, constant 'N' )
                , ( 0, constant 'O' )
                , ( 3, constant 'P' )
                , ( 0, constant 'Q' )
                , ( 0, constant 'R' )
                , ( 0, constant 'S' )
                , ( 3, constant 'T' )
                , ( 0, constant 'U' )
                , ( 0, constant 'V' )
                , ( 0, constant 'W' )
                , ( 0, constant 'X' )
                , ( 0, constant 'Y' )
                , ( 0, constant 'Z' )
                ]

        'Y' ->
            frequency
                [ ( 18, constant 'A' )
                , ( 7, constant 'B' )
                , ( 6, constant 'C' )
                , ( 6, constant 'D' )
                , ( 14, constant 'E' )
                , ( 7, constant 'F' )
                , ( 3, constant 'G' )
                , ( 10, constant 'H' )
                , ( 11, constant 'I' )
                , ( 1, constant 'J' )
                , ( 1, constant 'K' )
                , ( 4, constant 'L' )
                , ( 6, constant 'M' )
                , ( 3, constant 'N' )
                , ( 36, constant 'O' )
                , ( 4, constant 'P' )
                , ( 0, constant 'Q' )
                , ( 3, constant 'R' )
                , ( 19, constant 'S' )
                , ( 20, constant 'T' )
                , ( 1, constant 'U' )
                , ( 1, constant 'V' )
                , ( 12, constant 'W' )
                , ( 0, constant 'X' )
                , ( 2, constant 'Y' )
                , ( 0, constant 'Z' )
                ]

        'Z' ->
            frequency
                [ ( 1, constant 'A' )
                , ( 0, constant 'B' )
                , ( 0, constant 'C' )
                , ( 0, constant 'D' )
                , ( 3, constant 'E' )
                , ( 0, constant 'F' )
                , ( 0, constant 'G' )
                , ( 0, constant 'H' )
                , ( 1, constant 'I' )
                , ( 0, constant 'J' )
                , ( 0, constant 'K' )
                , ( 0, constant 'L' )
                , ( 0, constant 'M' )
                , ( 0, constant 'N' )
                , ( 0, constant 'O' )
                , ( 0, constant 'P' )
                , ( 0, constant 'Q' )
                , ( 0, constant 'R' )
                , ( 0, constant 'S' )
                , ( 0, constant 'T' )
                , ( 0, constant 'U' )
                , ( 0, constant 'V' )
                , ( 0, constant 'W' )
                , ( 0, constant 'X' )
                , ( 0, constant 'Y' )
                , ( 0, constant 'Z' )
                ]

        _ ->
            englishLetter
